/* ps5_sdk_core.h - PS5 handles
 * Generated by gen_known_sdk.py from live RAM EH offsets.
 */
#ifndef PS5_SDK_PS5_SDK_CORE_H
#define PS5_SDK_PS5_SDK_CORE_H

/* Module handles from live MODLIST / fw 13.00. */
#define EBOOT_BIN_HANDLE 0x0
#define LIBCINTERNAL_HANDLE                    0x2
#define SYSMODULE_HANDLE                       0x11
#define FIOS2_HANDLE                           0x13
#define C_HANDLE                               0x14
#define NET_HANDLE                             0x1e
#define IPMI_HANDLE                            0x2d
#define MBUS_HANDLE                            0x2e
#define REGMGR_HANDLE                          0x2f
#define RTC_HANDLE                             0x30
#define AVSETTING_HANDLE                       0x31
#define VIDEOOUT_HANDLE                        0x32
#define GNMDRIVER_HANDLE                       0x33
#define AUDIOOUT_HANDLE                        0x35
#define AUDIOIN_HANDLE                         0x39
#define AJM_HANDLE                             0x3c
#define PAD_HANDLE                             0x3d
#define CAMERA_HANDLE                          0x3e
#define NETCTL_HANDLE                          0x44
#define HTTP_HANDLE                            0x46
#define SSL_HANDLE                             0x48
#define NPCOMMON_HANDLE                        0x4a
#define NPMANAGER_HANDLE                       0x4b
#define NPWEBAPI_HANDLE                        0x77
#define SAVEDATA_HANDLE                        0x78
#define SYSTEMSERVICE_HANDLE                   0x79
#define USERSERVICE_HANDLE                     0x8a
#define COMMONDIALOG_HANDLE                    0x8b
#define SYSUTIL_HANDLE                         0x8d
#define SISRMGR_HANDLE                         0x8e
#define PNGENC_HANDLE                          0x93
#define APPCONTENT_HANDLE                      0x94
#define NPTROPHY_HANDLE                        0x96
#define GAMELIVESTREAMING_HANDLE               0x9d
#define REMOTEPLAY_HANDLE                      0x9f
#define SCREENSHOT_HANDLE                      0xa1
#define RESOURCEARBITRATOR_HANDLE              0xa2
#define AVCAP2_HANDLE                          0xa4
#define VIDEORECORDING_HANDLE                  0xa5
#define SHAREPLAY_HANDLE                       0xaa
#define COMPANIONHTTPD_HANDLE                  0xac
#define MSGDIALOG_HANDLE                       0xb5
#define SAVEDATADIALOG_HANDLE                  0xb7
#define PS2EMUMENUDIALOG_HANDLE                0xb9
#define KERNEL_HANDLE                          0x2001
#define LIBKERNEL_HANDLE 0x2001

#endif /* PS5_SDK_PS5_SDK_CORE_H */
